{
 "title": "ClamAV Dashboard",
 "description": "ClamAV Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(go_memstats_alloc_bytes, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(process_resident_memory_bytes, pod)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "ClamD Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virus Detected",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(virus_detected) (clamdproxy_files_scanned_total{virus_detected=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files Scanned",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(virus_detected) (clamdproxy_files_scanned_total{virus_detected=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http status 200",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (\n  promhttp_metric_handler_requests_total{code=\"200\"}\n)\n",
     "legendFormat": "status {{code}}"
    }
   ]
  },
  {
   "title": "Total File Scanned in size",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clamdproxy_files_size_bytes_total)",
     "legendFormat": "status {{code}}"
    }
   ]
  },
  {
   "title": "http status 500",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (\n  promhttp_metric_handler_requests_total{code=\"500\"}\n)\n",
     "legendFormat": "status {{code}}"
    }
   ]
  },
  {
   "title": "Backend Error Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (clamdproxy_backend_errors_total{job=\"clamdproxy\"})",
     "legendFormat": "status {{code}}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (clamdproxy_connections_total{job=\"clamdproxy\"})",
     "legendFormat": "status {{code}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (clamdproxy_active_connections{job=\"clamdproxy\"})",
     "legendFormat": "status {{code}}"
    }
   ]
  },
  {
   "title": "Commands Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(command) (clamdproxy_commands_total{allowed=\"true\"})",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Command Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(clamdproxy_files_scanned_total{job=\"clamdproxy\"}[1m]))",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}